package com.gon.kineapp.utils

object Constants {

    const val PATIENT_EXTRA = "PATIENT_EXTRA"
    const val SESSION_EXTRA = "SESSION_EXTRA"
    const val NAME_EXTRA = "NAME_EXTRA"
    const val BITMAP_EXTRA = "BITMAP_EXTRA"
    const val PHOTO_EXTRA = "PHOTO_EXTRA"
    const val PHOTO_TAG_EXTRA = "PHOTO_TAG_EXTRA"
    const val TIME_LINE_PHOTOS_EXTRA = "TIME_LINE_PHOTOS_EXTRA"
    const val VIDEO_EXTRA = "VIDEO_EXTRA"
    const val USER_EXTRA = "USER_EXTRA"
    const val ROUTINE_EXTRA = "ROUTINE_EXTRA"

    const val EXERCISE_TITLE_EXTRA = "EXERCISE_TITLE_EXTRA"
    const val EXERCISE_DESCRIPTION_EXTRA = "EXERCISE_DESCRIPTION_EXTRA"
    const val EXERCISE_DAYS_EXTRA = "EXERCISE_DAYS_EXTRA"
    const val EXERCISE_VIDEO_ID_EXTRA = "EXERCISE_VIDEO_ID_EXTRA"

    const val EXTERNAL_VIDEO_FOLDER = "KineAppVideos"

    const val REMOVED_PHOTO_CODE = 5000
    const val EDITED_SESSION_CODE = 5001
    const val EDITED_VIDEOS_CODE = 5002
    const val EDITED_ROUTINE_CODE = 5003

}